"""Architecture B: Separate Judge Agent.

Responsibility split in Arch B:
- Question generation  → RAGAgent.generate_check()  (has explanation + retrieved context)
- Verdict evaluation   → SeparateJudgeAgent.evaluate()  (adversarial CoT on its own model)

The judge runs on a dedicated, lighter model (e.g. gpt-4o-mini) to avoid
the leniency bias that arises when the same model grades its own output.
"""

import structlog

from src.agents.base import BaseAgent
from src.llm.base import BaseLLMClient
from src.models.feedback import JudgeVerdict

logger = structlog.get_logger()

JUDGE_SYSTEM_PROMPT = """\
You are a rigorous academic evaluator. Your job is to find gaps in understanding,
not to confirm that the learner did well.

Assume partial understanding is NOT sufficient. Only mark UNDERSTOOD if the learner
demonstrates the core concept without prompting.

You MUST follow this chain-of-thought evaluation process:

Step 1: What was the core concept the learner needed to demonstrate?
Step 2: What did the learner actually say or answer?
Step 3: Does the response contain the key concept? What is missing?
Step 4: Is this a genuine understanding signal or a surface guess?
Step 5: Verdict -- UNDERSTOOD or NOT_UNDERSTOOD, and why.
Step 6: If NOT_UNDERSTOOD, what specific concept or detail was absent from the
        original explanation that could have prevented this gap? Phrase this as a
        retrieval query fragment (e.g. "definition and mechanism of osmosis in plants").
        If UNDERSTOOD, write "none".

Respond in this exact format:
COT_STEP_1: <...>
COT_STEP_2: <...>
COT_STEP_3: <...>
COT_STEP_4: <...>
VERDICT: <UNDERSTOOD|NOT_UNDERSTOOD>
RATIONALE: <one-line summary>
RETRIEVAL_FEEDBACK: <retrieval query fragment, or "none">
"""


class SeparateJudgeAgent(BaseAgent):
    """Judge agent running on its own dedicated model (Architecture B).

    Only evaluates — question generation is handled by the RAG agent.
    Uses adversarial CoT to counter the leniency bias that arises when
    a model evaluates output it was involved in generating.
    """

    def __init__(self, llm: BaseLLMClient):
        super().__init__(llm)

    async def evaluate(
        self, question: str, learner_response: str, explanation: str, topic: str
    ) -> JudgeVerdict:
        """Evaluate the learner's response using adversarial CoT.

        Args:
            question: The comprehension check question generated by the RAG agent.
            learner_response: What the learner answered.
            explanation: The original explanation the RAG agent gave.
            topic: The topic being assessed.
        """
        user_msg = (
            f"Topic: {topic}\n"
            f"Explanation given to the learner: {explanation}\n"
            f"Comprehension question asked: {question}\n"
            f"Learner's response: {learner_response}\n\n"
            f"Evaluate using the required chain-of-thought process."
        )

        response = await self._llm.generate(
            system_prompt=JUDGE_SYSTEM_PROMPT,
            user_message=user_msg,
        )

        verdict = self._parse_verdict(response, question, learner_response)
        logger.info("arch_b.judge.evaluated", verdict=verdict.verdict, topic=topic)
        return verdict

    def _parse_verdict(
        self, response: str, question: str, learner_response: str
    ) -> JudgeVerdict:
        parsed = {}
        for line in response.strip().split("\n"):
            if ":" in line:
                key, _, value = line.partition(":")
                parsed[key.strip().upper()] = value.strip()

        raw_feedback = parsed.get("RETRIEVAL_FEEDBACK", "none")
        retrieval_feedback = "" if raw_feedback.lower() == "none" else raw_feedback

        return JudgeVerdict(
            verdict=parsed.get("VERDICT", "NOT_UNDERSTOOD"),
            cot_reasoning=response,
            check_mode="",
            question_asked=question,
            learner_response=learner_response,
            retrieval_feedback=retrieval_feedback,
        )
