"""Prompt version and candidate models."""

from datetime import datetime

from pydantic import BaseModel, Field


class PromptVersion(BaseModel):
    """A versioned prompt stored in the Prompt Registry."""

    version_id: str
    template: str
    grade: str = ""
    variant: str = "standard"          # standard, remedial, advanced
    status: str = "active"             # active, candidate, retired
    created_at: datetime = Field(default_factory=datetime.utcnow)
    metadata: dict = Field(default_factory=dict)
    # Used by the feedback-aware prompt selector to score suitability
    description: str = ""              # one-line description of teaching approach
    tags: list[str] = Field(default_factory=list)  # e.g. ["analogy", "conceptual"]


class PromptCandidate(BaseModel):
    """A prompt candidate generated by the governance loop for evaluation."""

    candidate_id: str
    parent_version_id: str
    template: str
    rationale: str = ""
    risk_score: float = 0.0
    experiment_results: dict = Field(default_factory=dict)
    status: str = "pending"            # pending, testing, promoted, rejected
